# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- develop
- feature/*

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- task: Docker@2
  inputs:
    containerRegistry: 'azuseacr0300'
    repository: $(Build.Repository.Name)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(Build.BuildNumber)
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '6fd166c1-674a-4d19-bf75-2a0dbea0a9f4'
    appType: 'webAppContainer'
    WebAppName: 'snipbiz'
    DockerNamespace: 'azuseacr0300.azurecr.io'
    DockerRepository: $(Build.Repository.Name)
    DockerImageTag: $(Build.BuildNumber)
